name: cell
description: >-
  A programming framework provides a comprehensive reactive programming 
  solution for Dart, with particular strength in managing complex state 
  and data flow in applications.

version: 1.0.0-rc.1

environment:
  sdk: '>=3.6.0 <4.0.0'

topics:
  - reactive
  - collection
  - codegen
  - framework
  - relation

repository: https://github.com/simon-m-lee/cell

documentation: https://pub.dev/documentation/cell/latest/

issue_tracker: https://github.com/simon-m-lee/cell/issues

workspace:
  - packages/cell

